### ISSUE TITLE
multiple assigning issue 

### ISSUE THREAD

**Issue by DreamWuGit** [zcash/halo2#645] opened 2022-08-25 10:23 UTC
we experienced assign same cells one more time by mistake, even though the result is OK(as long as last assign correct value ),  but I am wondering if multiple assigning can be regarding as error. if yes, halo2 had better to check this at the assigning or other stage & report it. that behavior can help developers to be aware of this case earlier.

**Comment by therealyingtong** [comment] 2022-09-12 08:54
This is a duplicate of https://github.com/zcash/halo2/issues/257.

**Closed by therealyingtong** 2022-09-12 08:54 UTC
