### ISSUE TITLE
Document circuit configuration process

### ISSUE THREAD

**Issue by parazyd** [zcash/halo2#512] opened 2022-03-02 14:00 UTC
Additionally, some explanations on necessary circuit configurations that are implied by gadgets but not initially known to external developers.

e.g.:

* Making pedersen commitments
* Verifying merkle path/root
* Witnessing bytes as bits
* Scalar arithmetic
* Public key derivation

**Comment by str4d** [comment] 2022-03-02 14:05
The gadget API part of this issue is a duplicate of #312. I've refined this issue to be about explaining circuit configurations.

**Closed by str4d** 2022-03-02 14:05 UTC
Labels: A-documentation
